### ISSUE TITLE
[PO]: Custom Heatsink Order

### ISSUE THREAD

**Issue by mtfunder** [precision-sustainable-ag/PlantMap3D-Hardware#14]
Place an order with sales@heatsinkonline.com for 10 more of the same heatsink we ordered with them last time.

There is an existing email thread @mtfunder can forward you.

You will need a quote, however this will be well under $5K so you do not need a formal PO.

##Partsbox Link##

https://partsbox.com/psa/parts/5g5nmzmda6kacbr57mfy0sk6aq

**Comment by kldriver** [comment]
@mtfunder If you send me the email thread for the exact heatsink, I can get things moving on this purchase

**Comment by mtfunder** [comment]
@kldriver I replied and CCd you to the email.
